# Pending Deployment

# FROM node:lts-alpine
# WORKDIR /usr/src/app
# COPY portafolio-testing/package*.json ./
# RUN ls -l
# RUN npm install
# COPY portafolio-testing ./
# RUN ls -l
# RUN npm run build
# COPY portafolio-testing/nodeServer.js dist/nodeServer.js
# WORKDIR /usr/src/app/dist
# EXPOSE 8080
# CMD [ "node", "nodeServer.js" ]
